kind: Deployment
apiVersion: apps/v1
metadata:
  name: ota-go-job
  namespace: ota
  labels:
    app: ota-go-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ota-go-job
  template:
    metadata:
      labels:
        app: ota-go-job
    spec:
      volumes:
        - name: vol-156396590221730716
          hostPath:
            path: /etc/localtime
            type: ''
        - name: vol-156396609000849049
          hostPath:
            path: /data/logs/ota-go-job
            type: ''
      containers:
        - name: ota-go-job
          image: 'swr.cn-east-2.myhuaweicloud.com/jinbaozheng/ota-go-job:latest-pro'
          env:
            - name: PAAS_APP_NAME
              value: ota-go-job
            - name: PAAS_NAMESPACE
              value: ota
            - name: args
              value: '--config.file.name=config-pro-k8s.yml'
          resources:
            limits:
              cpu: '0'
              memory: '0'
            requests:
              cpu: '0'
              memory: '0'
          volumeMounts:
            - name: vol-156396590221730716
              readOnly: true
              mountPath: /etc/localtime
            - name: vol-156396609000849049
              mountPath: /data/logs/ota-go-job
          livenessProbe:
            tcpSocket:
              port: 9040
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9040
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1