kind: Deployment
apiVersion: apps/v1
metadata:
  name: ota-go-trade
  namespace: ota
  labels:
    app: ota-go-trade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ota-go-trade
  template:
    metadata:
      labels:
        app: ota-go-trade
    spec:
      volumes:
        - name: vol-156396590221730716
          hostPath:
            path: /etc/localtime
            type: ''
        - name: vol-156396609000849049
          hostPath:
            path: /data/logs/ota-go-trade
            type: ''
      containers:
        - name: ota-go-trade
          image: 'swr.cn-east-2.myhuaweicloud.com/jinbaozheng/ota-go-trade:latest-pro'
          env:
            - name: PAAS_APP_NAME
              value: ota-go-trade
            - name: PAAS_NAMESPACE
              value: ota
            - name: args
              value: '--config.file.name=config-pro-k8s.yml'
          resources:
            requests:
              cpu: 200m
              memory: 50Mi
          volumeMounts:
            - name: vol-156396590221730716
              readOnly: true
              mountPath: /etc/localtime
            - name: vol-156396609000849049
              mountPath: /data/logs/ota-go-trade
          livenessProbe:
            tcpSocket:
              port: 9020
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9020
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.type
                    operator: NotIn
                    values:
                      - beta
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---
kind: Service
apiVersion: v1
metadata:
  name: ota-go-trade-svc
  namespace: ota
  labels:
    app: ota-go-trade
    name: ota-go-trade-svc
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 9020
      targetPort: 9020
  selector:
    app: ota-go-trade
  type: ClusterIP
  sessionAffinity: None
