kind: Deployment
apiVersion: apps/v1
metadata:
  name: ota-go-platform
  namespace: ota
  labels:
    app: ota-go-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ota-go-platform
  template:
    metadata:
      labels:
        app: ota-go-platform
    spec:
      volumes:
        - name: vol-156396590221730716
          hostPath:
            path: /etc/localtime
            type: ''
        - name: vol-156396609000849049
          hostPath:
            path: /data/logs/ota-go-platform
            type: ''
      containers:
        - name: ota-go-platform
          image: 'swr.cn-east-2.myhuaweicloud.com/jinbaozheng/ota-go-platform:latest-pro'
          env:
            - name: PAAS_APP_NAME
              value: ota-go-platform
            - name: PAAS_NAMESPACE
              value: ota
            - name: args
              value: '--config.file.name=config-pro-k8s.yml'
          resources:
            requests:
              cpu: 200m
              memory: 50Mi
          volumeMounts:
            - name: vol-156396590221730716
              readOnly: true
              mountPath: /etc/localtime
            - name: vol-156396609000849049
              mountPath: /data/logs/ota-go-platform
          livenessProbe:
            tcpSocket:
              port: 9010
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9010
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: default-secret
      schedulerName: default-scheduler
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.type
                    operator: NotIn
                    values:
                      - beta
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

---
kind: Service
apiVersion: v1
metadata:
  name: ota-go-platform-svc
  namespace: ota
  labels:
    app: ota-go-platform
    name: ota-go-platform-svc
spec:
  ports:
    - name: cce-service-0
      protocol: TCP
      port: 9010
      targetPort: 9010
  selector:
    app: ota-go-platform
  type: ClusterIP
  sessionAffinity: None
